### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by TessHuelskamp** [TessHuelskamp/huelskamp.io#1]
- [x] Something is wrong with my ANAME records (this is embarrassing) and I need to fix that.
- [x] Need to enable HTTPS
- [x] Latest update was written _in production_ so I really need to set up some sort of better solution to this.
- [x] Need to do some housekeeping on my server.
- [ ] Google sites says this isn't optimized well for mobile (even though it doesn't look bad) so I need to also investigate this.
- [ ] blog

**Comment by TessHuelskamp** [comment]
Website now pulls from this GitHub master branch once a day 🤷‍♀ 
Am happy with server config
